name: yamanis_fit
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  http:
  table_calendar: ^3.1.2
  firebase_core: ^4.6.0
  firebase_auth: 6.3.0
  cloud_firestore: 6.2.0
  youtube_player_flutter: 9.1.3
  cupertino_icons: ^1.0.8
  firebase_messaging: ^16.1.3
  shared_preferences: ^2.2.2

  intl: any
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

  firebase_core_platform_interface: any
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#11151C"
  image: assets/logos/logo_padding.png
  android_12:
    image: assets/logos/logo_padding.png
    color: "#11151C"

flutter:
  uses-material-design: true

  assets:
    - assets/logos/logo.png
    - assets/logos/logo_padding.png

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
